### ISSUE TITLE
CMAKE_INSTALL_<dir> paths assumed to be relative

### ISSUE THREAD

**Issue by Madouura** [ROCm/rocm-cmake#121] opened 2022-12-24 21:30 UTC
Please see: https://github.com/jtojnar/cmake-snips#assuming-cmake_install_dir-is-relative-path
For context: https://github.com/ROCm-Developer-Tools/hipamd/issues/55

Here is an example:
https://github.com/RadeonOpenCompute/rocm-cmake/blob/027404a8326da6e7e9338e0b81f9428660190724/share/rocm/cmake/ROCMInstallTargets.cmake#L87-L96
This assumes that ``CMAKE_INSTALL_<DIR>`` is relative, which is definitely not always the case.

**Comment by cgmb** [comment] 2022-12-28 19:12
The `PREFIX` option is not used anymore, so the problem is further down. I should talk with @lawruble13 about this, since I don't fully understand the purpose of `ROCMInstallTargets` vs. the built-in CMake export and install. With the /opt/rocm file reorganization completed, I wonder if we might be able to simplify our build code for this functionality.

**Comment by cgmb** [comment] 2023-01-09 18:30
I'm looking at my schedule for the next month and I'm not sure when I'm going to get a chance to really dig into this, so I'm marking this as help wanted. The problem is simple enough, but it's not immediately obvious to me how to fix this without breaking existing code.

**Comment by nartmada** [comment] 2024-04-30 01:52
@Madouura, has this issue been fixed?  Please close the ticket if the issue has been fixed.  Thanks.

**Comment by ppanchad-amd** [comment] 2024-07-18 19:57
@Madouura Closing ticket since there is no response.  Please re-open if you still encounter this issue. Thanks!

**Closed by ppanchad-amd** 2024-07-18 19:57 UTC
Labels: help wanted
